spring:
  application:
    name: batch
  config:
    import: classpath:common.yml
  main:
    web-application-type: none

ssutoday:
  crawler:
    fixed-delay: ${CRAWLER_FIXED_DELAY:60000}
    max-pages: ${CRAWLER_MAX_PAGES:2}
