spring:
  config:
    import: classpath:common.yml
  kafka:
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:ssutoday}
  main:
    web-application-type: none

ssutoday:
  firebase:
    credentials: ${FIREBASE_CREDENTIALS:firebase.json}
