spring:
  config:
    import: classpath:common.yml
  kafka:
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:ssutoday-push}
      auto-offset-reset: earliest

ssutoday:
  firebase:
    credentials: ${FIREBASE_CREDENTIALS:firebase.json}
