package kr.ac.ssu.ssutoday.core.attestation

/** 원문 토큰이나 외부 응답을 포함하지 않는 관찰/강제 모드 공통 판정. */
enum class AttestationVerdict {
    VERIFIED,
    MISSING,
    INVALID_INPUT,
    UNSUPPORTED_PLATFORM,
    NOT_CONFIGURED,
    PROVIDER_AUTHORIZATION_FAILED,
    PROVIDER_UNAVAILABLE,
    INVALID_RESPONSE,
    TOKEN_REJECTED,
    PACKAGE_MISMATCH,
    REQUEST_HASH_MISMATCH,
    TOKEN_EXPIRED,
    TOKEN_FROM_FUTURE,
    APP_UNRECOGNIZED,
    CERTIFICATE_MISMATCH,
    DEVICE_UNTRUSTED,
    CHALLENGE_REJECTED,
    CHALLENGE_STORE_UNAVAILABLE,
}
