spring:
  application:
    name: api
  config:
    import: classpath:common.yml
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

server:
  port: 8090

