spring:
  config:
    import: classpath:common.yml
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  jwt:
    secret: ${JWT_SECRET_KEY}
  kafka:
    consumer:
      auto-offset-reset: latest
      group-id: spring
  discord:
    webhook-url: ${DISCORD_WEBHOOK_URL:}

server:
  port: 80

ssutoday:
  recaptcha:
    secret-key: ${RECAPTCHA_SECRET_KEY}
    minimum-score: ${RECAPTCHA_MINIMUM_SCORE:0.5}
    allowed-hostnames: ${RECAPTCHA_ALLOWED_HOSTNAMES:}
